name: Build & Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go mod download
          go get github.com/spf13/cobra

      - name: Build for macOS
        run: |
          GOOS=darwin GOARCH=amd64 go build -o lorvi-darwin-amd64 .
          ls -l

      - name: Run Tests
        run: go test ./...

      - name: Run Security Scan (gosec)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.18.2
          gosec ./...

      - name: Run Vulnerability Check (govulncheck)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.0.1
          govulncheck ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lorvi-darwin-amd64
          path: lorvi-darwin-amd64

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Binary for Release
        run: |
          GOOS=darwin GOARCH=amd64 go build -o lorvi-darwin-amd64 .
          ls -l

      - name: Create Release Artifact
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./lorvi-darwin-amd64