name: Build & Security Scan

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go mod download
          go get github.com/spf13/cobra

      - name: Build for macOS
        run: |
          VERSION=$(git describe --tags --always --dirty)
          COMMIT=$(git rev-parse --short HEAD)
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/muzaparoff/lorvi/cmd.Version=${VERSION} -X github.com/muzaparoff/lorvi/cmd.Commit=${COMMIT}" -o lorvi-darwin-amd64 .
          ls -l

      - name: Run Tests
        run: go test ./...

      - name: Run Security Scan (gosec)
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@v2.18.2
          gosec ./...

      - name: Run Vulnerability Check (govulncheck)
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.0.1
          govulncheck ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lorvi-darwin
          path: |
            lorvi-darwin-amd64
            lorvi-darwin-arm64
          if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/download-artifact@v4
        with:
          name: lorvi-darwin
          path: .

      - name: Generate Checksums
        run: |
          sha256sum lorvi-darwin-* > checksums.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lorvi-darwin-amd64
            lorvi-darwin-arm64
            checksums.txt
          generate_release_notes: true