name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build and Package
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          GOOS=darwin GOARCH=amd64 go build -o lorvi-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -o lorvi-darwin-arm64
          tar czf lorvi-$VERSION-darwin-amd64.tar.gz lorvi-darwin-amd64
          tar czf lorvi-$VERSION-darwin-arm64.tar.gz lorvi-darwin-arm64

      - name: Upload to GitHub Packages
        uses: actions/upload-artifact@v4
        with:
          name: lorvi-packages
          path: lorvi-*.tar.gz
