name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.semantic.outputs.released }}
      version: ${{ steps.semantic.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Semantic Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits
          npx semantic-release

      - name: Setup Go
        if: steps.semantic.outputs.released == 'true'
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Release
        if: steps.semantic.outputs.released == 'true'
        run: |
          VERSION=${{ steps.semantic.outputs.version }}
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/muzaparoff/lorvi/cmd.Version=v${VERSION}" -o lorvi-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/muzaparoff/lorvi/cmd.Version=v${VERSION}" -o lorvi-darwin-arm64
          tar czf lorvi-v${VERSION}-darwin-amd64.tar.gz lorvi-darwin-amd64
          tar czf lorvi-v${VERSION}-darwin-arm64.tar.gz lorvi-darwin-arm64

      - name: Upload Release Assets
        if: steps.semantic.outputs.released == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.semantic.outputs.version }}
          files: |
            lorvi-v${{ steps.semantic.outputs.version }}-darwin-*.tar.gz
          generate_release_notes: true
